use vk;
show tables;
select * from user;
select * from like_media;  
select * from like_user WHERE from_user_id = to_user_id; 
delete from like_user WHERE from_user_id = 21; 
delete from like_user WHERE from_user_id = 31; 
delete from like_user WHERE from_user_id = 37; 
select * from like_user WHERE from_user_id = to_user_id; 
update ignore post set updated_at = null  where updated_at = '0000-00-00 00:00:00';
update ignore user set updated_at = null  where updated_at = '0000-00-00 00:00:00';
update ignore friend_request set updated_at = null  where updated_at = '0000-00-00 00:00:00';
update ignore message set updated_at = null  where updated_at = '0000-00-00 00:00:00';
select * from  `friend_request` where `status` != 0 and updated_at is null;
update `friend_request` set updated_at = NOW()  where `status` != 0 and updated_at is null;
select * from  `friend_request`;
select * from  `post` where id % 2;
update  `post` set community_id = null where id % 2;
update  `profile` set media_id = null where user_id % 3;
select * from  profile;
delete from message where id > 5 AND id<10;
select * from  message;
insert message values (101,22,45,'sdfjhgreikgkjuerg',now(),Now(),null,null,3);